### ISSUE TITLE
Async

### ISSUE THREAD

**Issue by gigavinyl** [duct-framework/duct#100]
Hi! Does duct support async either through core.async or manifold like aleph and pedestal? If not, could support be added?

**Comment by gigavinyl** [comment]
Oh, I found the aleph module!

**Comment by weavejester** [comment]
Yes, there's a library for [Aleph](https://github.com/duct-framework/server.http.aleph) and [HTTP-Kit](https://github.com/duct-framework/server.http.http-kit), both of which have asynchronous HTTP and websocket support. In addition, the default [Jetty](https://github.com/duct-framework/server.http.http-kit) adapter supports asynchronous HTTP to a lesser extent.
