### ISSUE TITLE
Websockets 

### ISSUE THREAD

**Issue by gigavinyl** [duct-framework/duct#101]
Does this project support websockets (either only through jetty or through other servers as well)? If not, could support be added?

**Comment by weavejester** [comment]
Yes, there's a library for [Aleph](https://github.com/duct-framework/server.http.aleph) and [HTTP-Kit](https://github.com/duct-framework/server.http.http-kit), both of which have websocket support.

**Comment by gigavinyl** [comment]
Awesome! Could you provide an example with aleph? I'm not sure where to throw the `(aleph/websocket-connection req)` function

**Comment by weavejester** [comment]
If you create a new Duct project with:

    lein new duct foo +web +example

Or:

    lein new duct foo +web +example +ataraxy

Then you'll see an example of how to fit a handler into a Duct project. The actual specifics of how to get the websocket vary between the different adapters, so you'll need to consult their documentation.
