### ISSUE TITLE
Logo for duct - suggested designs

### ISSUE THREAD

**Issue by jr0cket** [duct-framework/duct#107]
If a logo for the duct project would be of interest, are any of the designs here meaningful to the maintainers of this project.

https://github.com/practicalli/graphic-design/blob/master/duct-logo-designs.svg

Adjustments to the designs can be made if any of them are of interest.

Logos are created with the Open Source Inkscape software. If any of these designs are interested they would be donated to the project under a creative commons license, along with original SVG assets.

Thank you.

**Comment by weavejester** [comment]
Thank you for the logo suggestions, but I'm afraid these aren't the style of design I'd want for Duct.

**Comment by jr0cket** [comment]
Thank you for considering these designs.  If you wish to share the style of designs you are looking for, I can review and see if I can help.

Thanks again
