### ISSUE TITLE
Clj-kondo convention, does it conflict with Duct?

### ISSUE THREAD

**Issue by borkdude** [duct-framework/duct#110]
I'm thinking of a convention for [clj-kondo](https://github.com/borkdude/clj-kondo/), a Clojure linter by which library authors can export specific configuration for their libraries.

E.g. from the perspective of the library repo:

```
src/clj-kondo/config.edn
src/clj-kondo/hooks/rum.clj
``` 

So the `clj-kondo` directory will end up on the classpath and will be detected by clj-kondo. Then the `config.edn` config file will be merged into the user's clj-kondo configuration.

My question: does this somehow conflict with Duct's notion of a config.edn file?

See: https://github.com/borkdude/clj-kondo/issues/992

**Comment by weavejester** [comment]
You can put Duct's configuration file wherever you want, but by default the template puts the configuration in `<project-ns>/config.edn`. I don't think this conflicts with anything you're suggesting.

**Comment by borkdude** [comment]
Thanks.
