### ISSUE TITLE
How to rename the handler?

### ISSUE THREAD

**Issue by johanhaleby** [duct-framework/duct#50]
In previous versions of Duct you could rename the handler key from `:app` to something else when starting the jetty-server by doing:

```clojure
(jetty-server config {:app :handler-name})
```

What's the equivalent of doing this in `system.edn`?

**Comment by weavejester** [comment]
The same way as before. In your `system.edn` file there's a map of `:dependencies`. If you use maps instead of vectors for the values, you can rename keys. The `:dependencies` key is passed directly to the `system-using` function in Component.

**Comment by johanhaleby** [comment]
Thanks that works!
