### ISSUE TITLE
Config is not included correctly in (dev) when project name contain '-'

### ISSUE THREAD

**Issue by tentamen** [duct-framework/duct#54]
I create new `hello-duct` project using lein command: `lein new duct-alpha hello-duct`, then `lein duct setup`.  It generate `dev.edn` file like this:

```clj
{:duct.core/environment :development
 :duct.core/include ["hello-duct/config"]}
```
I think config path should be `hello_duct/config`,  _ instead of -, so it could include config from resources.

**Comment by weavejester** [comment]
Yes, you're right. The namespace is placed here when it should be the path.
