### ISSUE TITLE
The combination +api +ataraxy +cljs +example +site +heroku +postgres doesn't work

### ISSUE THREAD

**Issue by dpom** [duct-framework/duct#66]
Hi,

I try to create a project with:
lein new duct-alpha testduct +api +ataraxy +cljs +example +site +heroku +postgres
cd testduct
lein duct setup

In the  repl the (dev) call returns with the error:

CompilerException clojure.lang.ExceptionInfo: Call to clojure.core/refer-clojure did not conform to spec:
In: [2 1] val: :as fails at: [:args :exclude :op :quoted-spec :spec] predicate: #{:exclude}
In: [2 1] val: :as fails at: [:args :only :op :quoted-spec :spec] predicate: #{:only}
In: [2 1] val: :as fails at: [:args :rename :op :quoted-spec :spec] predicate: #{:rename}
In: [2] val: (quote :as) fails at: [:args :exclude :op :spec] predicate: #{:exclude}
In: [2] val: (quote :as) fails at: [:args :only :op :spec] predicate: #{:only}
In: [2] val: (quote :as) fails at: [:args :rename :op :spec] predicate: #{:rename}
:clojure.spec.alpha/spec  #object[clojure.spec.alpha$regex_spec_impl$reify__1200 0xf301248 "clojure.spec.alpha$regex_spec_impl$reify__1200@f301248"]
:clojure.spec.alpha/value  ((quote :exclude) (quote [reduce into merge map take partition partition-by bounded-count]) (quote :as) (quote core))
:clojure.spec.alpha/args  ((quote :exclude) (quote [reduce into merge map take partition partition-by bounded-count]) (quote :as) (quote core))
 #:clojure.spec.alpha{:problems ({:path [:args :exclude :op :spec], :pred #{:exclude}, :val (quote :as), :via [], :in [2]} {:path [:args :exclude :op :quoted-spec :spec], :pred #{:exclude}, :val :as, :via [], :in [2 1]} {:path [:args :only :op :spec], :pred #{:only}, :val (quote :as), :via [], :in [2]} {:path [:args :only :op :quoted-spec :spec], :pred #{:only}, :val :as, :via [], :in [2 1]} {:path [:args :rename :op :spec], :pred #{:rename}, :val (quote :as), :via [], :in [2]} {:path [:args :rename :op :quoted-spec :spec], :pred #{:rename}, :val :as, :via [], :in [2 1]}), :spec #object[clojure.spec.alpha$regex_spec_impl$reify__1200 0xf301248 "clojure.spec.alpha$regex_spec_impl$reify__1200@f301248"], :value ((quote :exclude) (quote [reduce into merge map take partition partition-by bounded-count]) (quote :as) (quote core)), :args ((quote :exclude) (quote [reduce into merge map take partition partition-by bounded-count]) (quote :as) (quote core))}, compiling:(clojure/core/async.clj:9:1) 
user=>

**Comment by iperdomo** [comment]
@dpom this works fine if you don't use `duct-alpha`

````
$ lein new duct testduct +api +ataraxy +cljs +example +site +heroku +postgres
Generating a new Duct project named testduct...
Run 'lein duct setup' in the project directory to create local config files.

$ cd testduct/

$ lein duct setup
Created profiles.clj
Created .dir-locals.el
Created dev/resources/local.edn
Created dev/src/local.clj

````

**Comment by dpom** [comment]
Thanks, indeed it works. What are differences between duct and duct-alpha?

**Comment by weavejester** [comment]
One is the released version, the other is the old alpha.
