### ISSUE TITLE
dir locals broken with CIDER 0.18.0

### ISSUE THREAD

**Issue by ccann** [duct-framework/duct#79]
Create a new duct project and run `lein duct setup`. Open the project in emacs, jack in CIDER, then run `cider-ns-refresh` => "Don't know how to make a localized variable an alias".

solution here: https://stackoverflow.com/questions/52191455/calling-cider-refresh-shows-dont-know-how-to-make-a-localized-variable-an-alia

new `.dir-locals.el`:

```emacs-lisp
((nil . ((cider-ns-refresh-before-fn . "integrant.repl/suspend")
         (cider-ns-refresh-after-fn  . "integrant.repl/resume"))))
```

Not sure what a good option is for making these local variables work with multiple versions of CIDER.

**Comment by weavejester** [comment]
I don't think we need to worry too much about supporting older versions of CIDER, as these are just local files that can be changed if someone really needs to stick with an older version, for whatever reason.

I've updated the `.dir-locals.el` template. Thanks for the report!
