### ISSUE TITLE
#duct/resource not working with ragtime migrations

### ISSUE THREAD

**Issue by admarrs** [duct-framework/duct#82]
Not sure if this is the correct place to post this. Trying to get ragtime migrations working with Duct core 0.7.0-beta2 and I get the following:

No implementation of method: :get-string of protocol: #'duct.migrator.ragtime/StringSource found for class: duct.core.resource.Resource

relevant config is:

:duct.migrator/ragtime
  { :migrations [#ig/ref :app.migration/create-table-users]}

  [:duct.migrator.ragtime/sql :app.migration/create-table-users]
  { :up   [#duct/resource "migrations/000-create-table-users.sql"]
    :down [#duct/resource "migrations/000-drop-table-users.sql"]}

This worked fine with Duct Core 0.6.2

**Comment by weavejester** [comment]
Thanks for the report. It looks like `:duct.migrator/ragtime` needs to be updated.
