### ISSUE TITLE
How to create a key with a constant value

### ISSUE THREAD

**Issue by viebel** [duct-framework/duct#96]
I would like to have in my configuration a key (e.g. `:location-of-assets`) with a constant value where the value could be overriden by local and dev files.

How can I achieve that without having to write a multimethod `init-key` that handles my`:location-of-assets`?

**Comment by weavejester** [comment]
You can derive a key from `:duct/const` if you want a constant.

**Comment by viebel** [comment]
Thanks. This is exactly what I was looking for.
Should it be documented somewhere?
