### ISSUE TITLE
Question: considered applying for Clojurists Together?

### ISSUE THREAD

**Issue by teodorlu** [duct-framework/duct#97]
Hello, @weavejester!

I think Duct is one of the most high-quality, under-appreciated pieces of the Clojure web development ecosystem, but from my point of view, it could use work on a cohesive guide, and how to handle common web development use-cases with Duct. The [documentation for Luminus][1] is a good example, in my opinion.

Have you considered applying for [funding from Clojurists Together][2]?

Teodor

[1]: http://www.luminusweb.net/docs
[2]: http://www.luminusweb.net/docs

**Comment by weavejester** [comment]
I floated the idea. The feedback I received was that working on a more widely used project like Ring would be more useful. However, currently I haven't much time to spend on either project, but I'm hoping that will change soon.

**Comment by teodorlu** [comment]
I see. Thanks for your reply.

I see the argument for investing in Ring, given its use. It might just be me, but I have this feeling that I can't shake that Duct might be what we need to "pull together" the ecosystem. Take how we reload our code. We keep reloading in new ways, but we could have formulated those was _within_ Duct's frame, and at the same time had more control, since Duct lets us provide the input for the reload. For instance, I really liked being able to refresh my migrations when working on database design; feels like Figwheel for a PostgreSQL data model.

I don't know how much Duct is used by others, though. I've been playing with the idea of a cohesive set of Duct docs on cljdoc, focused on common use-cases rather than what building blocks are provided, Luminus style. Which I think could lead to traction. cljdoc seems to be able to pull in namespace docs from different projects, so that it's simple to provide a top-level story for how you create value with this, and then link out to all the optional building blocks that Duct provides.

Glad to hear you've considered it, and I guess you can take this as a vote of Duct on Clojurists Together being a good idea. And if it isn't Duct, I hope you get a funding opportunity to work on some of the other pieces of Clojure's web development ecosystem that you've created!

I've got my question answered, so I'm closing this. Ping me any time if you wish to discuss further.

Teodor

**Comment by asiergaldos** [comment]
Clojurists Together survey results show that the community has interest in Duct. 

https://mailchi.mp/d2c85f828d27/q4-survey-results-529187?e=51c6277d61

We leverage it in our projects and have created several duct modules as well:

https://github.com/magnetcoop

We would be happy to contribute.

**Comment by teodorlu** [comment]
@asiergaldos Thanks for the link to the newsletter. Glad to see that it's up there, and that you and others are interested in using Duct, and seeing it funded.

In what way would you be happy to contribute?

**Comment by asiergaldos** [comment]
@teodorlu - we have contributed to a new feature (external profiles), but we could help with documentation as well. 

Our current duct-based commercial projects are on development at the moment, once we deploy to prod we could write blog posts.

In the meantime we continue to release and maintain duct modules in our github account.

What else could we contribute...? 

IMHO, Duct deserves a logo and site. We can help with both.

**Comment by teodorlu** [comment]
> IMHO, Duct deserves a logo and site. We can help with both.

I believe that would be very helpful. @weavejester should probably have a say in the matter too.

> Our current duct-based commercial projects are on development at the moment, once we deploy to prod we could write blog posts.

I'll definitely be interested in reading those. Good luck on finalization!
