### ISSUE TITLE
Wiki Contributions

### ISSUE THREAD

**Issue by ccann** [duct-framework/duct#98]
Hello,

I just now contributed a couple sections to the Configuration wiki page. I'm not entirely sure of guidelines for contributing to the wiki, but I looked at the page's history and folks seem to edit when appropriate. Hopefully my contribution is okay!

Do you think it's worth adding a bullet to the Contribution Guidelines addressing the Wiki pages?

**Comment by weavejester** [comment]
A wiki is made to be publically editable. If there are issues the changes can always be reverted, and if I want more control I can always write documents and put them on a website or repo. So use your best judgement when editing the wiki; what you've put already seems fine.
